name = "bullet/account-abstraction"
version = "0.0.1"
compiler = "v1.1.10"
plutus = "v3"
license = "Apache-2.0"
description = "Aiken contracts for project 'bullet/account-abstraction'"

[repository]
user = "bullet"
project = "account-abstraction"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "v2.2.0"
source = "github"

[[dependencies]]
name = "aiken-lang/fuzz"
version = "v2.1.1"
source = "github"

[config.default]
bullet_hash = "totally_valid"
nonce_bullet_hash = "totally_valid_nonce"
proxy_hash = "valid_proxy"
stake_proxy_hash = "staking_proxy"
new_user_tx_hash = "new_guy_in_town"
new_user_output_index = 0
one_shot_tx_hash = "one_shot_one_kill"
one_shot_output_index = 0
one_shot_mint_hash = "the_best_mint_ever"
namespace = "Bullet"

[config.preview]
new_user_output_index = 1
one_shot_output_index = 0
namespace = "Bullet"

[config.preview.bullet_hash]
bytes = "3e8b3d0bda81efcd1ce86d17b7764e55551cec6783f90bbc31069d69"
encoding = "hex"

[config.preview.nonce_bullet_hash]
bytes = "37d20d7f8ff4bc0cf3bfae904ec92ff8d306bc964be0d94767b3cdc4"
encoding = "hex"

[config.preview.proxy_hash]
bytes = "b04621841bec49b38d231d3edb83d09dd385a81903927e467185f101"
encoding = "hex"

[config.preview.stake_proxy_hash]
bytes = "d86bb152b638bf63db6d44aee0c3ff1818e13949cc4130ad5d459d57"
encoding = "hex"

[config.preview.new_user_tx_hash]
bytes = "0788cbca89f1a7442f0ed538d5d30ffee1014d367c1bbba4b13305b7bd8a36b7"
encoding = "hex"

[config.preview.one_shot_tx_hash]
bytes = "0000000000000000000000000000000000000000000000000000000000000000"
encoding = "hex"

[config.preview.one_shot_mint_hash]
bytes = "a704753ea2f639e46909d18cb666e0fdc5e602f9a353e6b94fb1d29b"
encoding = "hex"
